import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { colors } from '../../../theme/tokens';
import { productCopy } from '../../../content/productCopy';

export function SettingsScreen({ onOpenBackup }: { onOpenBackup: () => void }) {
  return <View style={styles.screen}><View style={styles.header}><Text accessibilityRole="header" style={styles.heading}>{productCopy.settings.heading}</Text></View><ScrollView contentContainerStyle={styles.content}><Text style={styles.section}>BACKUP</Text><Pressable accessibilityRole="button" accessibilityLabel={productCopy.settings.backupTitle} onPress={onOpenBackup} style={({ pressed }) => [styles.row, pressed && styles.pressed]}><View style={styles.icon}><Ionicons name="cloud-upload-outline" size={21} color={colors.primary} /></View><View style={styles.copy}><Text style={styles.title}>{productCopy.settings.backupTitle}</Text><Text style={styles.meta}>{productCopy.settings.backupMessage}</Text></View><Ionicons name="chevron-forward" size={18} color={colors.muted} /></Pressable><Text style={styles.section}>DEVICE</Text><View style={styles.row}><View style={styles.icon}><Ionicons name="shield-checkmark-outline" size={21} color={colors.primary} /></View><View style={styles.copy}><Text style={styles.title}>{productCopy.settings.deviceTitle}</Text><Text style={styles.meta}>{productCopy.settings.deviceMessage}</Text></View></View></ScrollView></View>;
}

const styles = StyleSheet.create({ screen: { flex: 1 }, header: { padding: 22 }, heading: { color: colors.text, fontSize: 30, fontWeight: '700', letterSpacing: -.7 }, content: { width: '100%', maxWidth: 760, alignSelf: 'center', padding: 22, paddingTop: 0 }, section: { color: colors.muted, fontSize: 12, fontWeight: '700', letterSpacing: 1.1, marginTop: 20, marginBottom: 9 }, row: { minHeight: 78, padding: 14, gap: 12, flexDirection: 'row', alignItems: 'center', borderRadius: 14, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, icon: { width: 42, height: 42, borderRadius: 10, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.raised }, copy: { flex: 1 }, title: { color: colors.text, fontSize: 16, fontWeight: '600' }, meta: { color: colors.muted, fontSize: 13, lineHeight: 18, marginTop: 3 }, pressed: { opacity: .72 } });
