const { withProjectBuildGradle } = require('expo/config-plugins');

const marker = '// @generated by withShortAndroidCmakePaths';

const snippet = `${marker}
subprojects { subproject ->
  plugins.withId('com.android.library') {
    android.externalNativeBuild.cmake.buildStagingDirectory = file("\${rootDir}/.cxx/\${subproject.path.replace(':', '_')}")
  }
  plugins.withId('com.android.application') {
    android.externalNativeBuild.cmake.buildStagingDirectory = file("\${rootDir}/.cxx/\${subproject.path.replace(':', '_')}")
  }
}
`;

function withShortAndroidCmakePaths(config) {
  return withProjectBuildGradle(config, (gradleConfig) => {
    if (!gradleConfig.modResults.contents.includes(marker)) {
      gradleConfig.modResults.contents =
        gradleConfig.modResults.contents.replace(
          /\napply plugin: "expo-root-project"/,
          `\n${snippet}\napply plugin: "expo-root-project"`,
        );
    }

    return gradleConfig;
  });
}

module.exports = withShortAndroidCmakePaths;
