import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import type { Screen } from '../../navigation/types';
import { colors } from '../../theme/tokens';

type Props = { desktop: boolean; screen: Screen; onNavigate: (screen: Screen) => void };
export function AppNavigation({ desktop, screen, onNavigate }: Props) {
  const items = <><NavItem desktop={desktop} label="Medias" icon="videocam-outline" active={screen.name === 'media'} onPress={() => onNavigate({ name: 'media' })} /><NavItem desktop={desktop} label="AutoSync" icon="cloud-upload-outline" active={screen.name === 'autosync'} onPress={() => onNavigate({ name: 'autosync' })} /></>;
  return desktop ? <View style={styles.sidebar}><View style={styles.logo}><View style={styles.logoMark}><Ionicons name="cloud-outline" size={19} color={colors.primary} /></View><Text style={styles.logoText}>Move Sync</Text></View><Text style={styles.sectionLabel}>LIBRARY</Text><View style={styles.nav}>{items}</View></View> : screen.name !== 'player' ? <View style={styles.bottom}>{items}</View> : null;
}
function NavItem({ desktop, label, icon, active, onPress }: { desktop: boolean; label: string; icon: 'videocam-outline' | 'cloud-upload-outline'; active: boolean; onPress: () => void }) { return <Pressable accessibilityRole="button" accessibilityState={{ selected: active }} onPress={onPress} style={[styles.item, desktop ? styles.sidebarItem : styles.bottomItem, active && styles.active]}><Ionicons name={icon} size={19} color={active ? colors.primary : colors.muted} /><Text style={[styles.itemText, active && styles.activeText]}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ sidebar: { width: 236, paddingHorizontal: 16, paddingTop: 28, borderRightWidth: 1, borderRightColor: colors.border, backgroundColor: '#0a131d' }, bottom: { height: 72, paddingHorizontal: 16, borderTopWidth: 1, borderTopColor: colors.border, backgroundColor: '#0a131d', flexDirection: 'row', gap: 8 }, logo: { height: 42, flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 8, marginBottom: 42 }, logoMark: { width: 27, height: 27, borderRadius: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: '#11253a' }, logoText: { color: colors.text, fontSize: 16, fontWeight: '700', letterSpacing: -.2 }, sectionLabel: { color: '#6f8194', fontSize: 10, fontWeight: '700', letterSpacing: 1.35, paddingHorizontal: 12, marginBottom: 10 }, nav: { gap: 4 }, item: { minHeight: 46, borderRadius: 9, gap: 10, flexDirection: 'row', alignItems: 'center' }, sidebarItem: { paddingHorizontal: 12, justifyContent: 'flex-start' }, bottomItem: { flex: 1, paddingHorizontal: 13, justifyContent: 'center' }, active: { backgroundColor: '#142b42' }, itemText: { color: colors.muted, fontSize: 14, fontWeight: '600' }, activeText: { color: colors.text } });
