import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import type { Screen } from '../../navigation/types';
import { colors } from '../../theme/tokens';
import { productCopy } from '../../content/productCopy';

type Props = { desktop: boolean; screen: Screen; onNavigate: (screen: Screen) => void };
export function AppNavigation({ desktop, screen, onNavigate }: Props) {
  // Navigation decision: use S4's desktop side rail. It supports the cloud-library
  // context and account area better than S3's compact top navigation.
  const desktopItems = <><NavItem desktop label={productCopy.navigation.videos} icon="videocam-outline" active={screen.name === 'videos'} onPress={() => onNavigate({ name: 'videos' })} /><NavItem desktop label={productCopy.navigation.collections} icon="folder-open-outline" active={screen.name === 'collections'} onPress={() => onNavigate({ name: 'collections' })} /><NavItem desktop label={productCopy.navigation.backup} icon="cloud-upload-outline" active={screen.name === 'backup'} onPress={() => onNavigate({ name: 'backup' })} /></>;
  const mobileItems = <><NavItem desktop={false} label={productCopy.navigation.videos} icon="videocam-outline" active={screen.name === 'videos'} onPress={() => onNavigate({ name: 'videos' })} /><NavItem desktop={false} label={productCopy.navigation.backup} icon="cloud-upload-outline" active={screen.name === 'backup'} onPress={() => onNavigate({ name: 'backup' })} /><NavItem desktop={false} label={productCopy.navigation.settings} icon="settings-outline" active={screen.name === 'settings'} onPress={() => onNavigate({ name: 'settings' })} /></>;
  return desktop ? <View style={styles.sidebar}><View style={styles.logo}><View style={styles.logoMark}><Ionicons name="cloud-outline" size={19} color={colors.primary} /></View><Text style={styles.logoText}>{productCopy.appName}</Text></View><View style={styles.nav}>{desktopItems}</View></View> : screen.name !== 'player' ? <View style={styles.bottom}>{mobileItems}</View> : null;
}
function NavItem({ desktop, label, icon, active, onPress }: { desktop: boolean; label: string; icon: 'videocam-outline' | 'folder-open-outline' | 'cloud-upload-outline' | 'settings-outline'; active: boolean; onPress: () => void }) { return <Pressable accessibilityRole="button" accessibilityState={{ selected: active }} onPress={onPress} style={[styles.item, desktop ? styles.sidebarItem : styles.bottomItem, active && styles.active]}><Ionicons name={icon} size={19} color={active ? colors.primary : colors.muted} /><Text style={[styles.itemText, active && styles.activeText]}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ sidebar: { width: 236, paddingHorizontal: 16, paddingTop: 28, borderRightWidth: 1, borderRightColor: colors.border, backgroundColor: '#0a131d' }, bottom: { height: 72, paddingHorizontal: 16, borderTopWidth: 1, borderTopColor: colors.border, backgroundColor: '#0a131d', flexDirection: 'row', gap: 8 }, logo: { height: 42, flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 8, marginBottom: 32 }, logoMark: { width: 27, height: 27, borderRadius: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: '#11253a' }, logoText: { color: colors.text, fontSize: 16, fontWeight: '700', letterSpacing: -.2 }, nav: { gap: 4 }, item: { minHeight: 46, borderRadius: 9, gap: 10, flexDirection: 'row', alignItems: 'center' }, sidebarItem: { paddingHorizontal: 12, justifyContent: 'flex-start' }, bottomItem: { flex: 1, paddingHorizontal: 8, justifyContent: 'center' }, active: { backgroundColor: '#142b42' }, itemText: { color: colors.muted, fontSize: 14, fontWeight: '600' }, activeText: { color: colors.text } });
