import type { PropsWithChildren, ReactNode } from 'react';
import { StyleSheet, Text, View, type StyleProp, type ViewStyle } from 'react-native';
import { theme, textStyles } from '../../theme/tokens';
import { useResponsive } from '../../hooks/useResponsive';
type Width = keyof typeof theme.content;
export function ContentFrame({ children, width = 'default', style }: PropsWithChildren<{ width?: Width; style?: StyleProp<ViewStyle> }>) { return <View style={[styles.frame, { maxWidth: theme.content[width] }, style]}>{children}</View>; }
export function PageHeader({ title, description, action, width = 'default' }: { title: string; description?: string; action?: ReactNode; width?: Width }) { return <ContentFrame width={width} style={styles.pageHeader}><View style={styles.headerCopy}><Text accessibilityRole="header" style={styles.pageTitle}>{title}</Text>{description ? <Text style={styles.description}>{description}</Text> : null}</View>{action ? <View style={styles.headerAction}>{action}</View> : null}</ContentFrame>; }
export function Toolbar({ children, width = 'default', style }: PropsWithChildren<{ width?: Width; style?: StyleProp<ViewStyle> }>) { return <ContentFrame width={width} style={[styles.toolbar, style]}>{children}</ContentFrame>; }
export function SectionHeader({ title, action }: { title: string; action?: ReactNode }) { return <View style={styles.sectionHeader}><Text accessibilityRole="header" style={styles.sectionTitle}>{title}</Text>{action}</View>; }
export function ResponsiveStack({ children, gap = 'md', style }: PropsWithChildren<{ gap?: keyof typeof theme.space; style?: StyleProp<ViewStyle> }>) { return <View style={[{ gap: theme.space[gap] }, style]}>{children}</View>; }
export function ResponsiveGrid({ children, style }: PropsWithChildren<{ style?: StyleProp<ViewStyle> }>) { const { isMobile } = useResponsive(); return <View style={[styles.grid, isMobile && styles.mobileGrid, style]}>{children}</View>; }
export function DetailPanel({ children, style }: PropsWithChildren<{ style?: StyleProp<ViewStyle> }>) { return <View style={[styles.detailPanel, style]}>{children}</View>; }
export function StatusRow({ icon, label, value, tone = 'default' }: { icon?: ReactNode; label: string; value: string; tone?: 'default' | 'accent' | 'success' | 'warning' | 'danger' }) { const color = tone === 'success' ? theme.color.success : tone === 'warning' ? theme.color.warning : tone === 'danger' ? theme.color.danger : tone === 'accent' ? theme.color.accent : theme.color.textSecondary; return <View style={styles.statusRow}>{icon ? <View>{icon}</View> : null}<Text style={styles.statusLabel}>{label}</Text><Text style={[styles.statusValue, { color }]} numberOfLines={2}>{value}</Text></View>; }
const styles = StyleSheet.create({ frame: { width: '100%', alignSelf: 'center', paddingHorizontal: theme.space.lg }, pageHeader: { minHeight: 120, paddingTop: theme.space.xl, paddingBottom: theme.space.lg, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: theme.space.md }, headerCopy: { flex: 1, gap: theme.space.xs }, headerAction: { flexShrink: 0 }, pageTitle: textStyles.pageTitle, description: textStyles.meta, toolbar: { minHeight: theme.size.touch, flexDirection: 'row', alignItems: 'center', gap: theme.space.sm, paddingBottom: theme.space.lg }, sectionHeader: { minHeight: theme.size.touch, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: theme.space.sm }, sectionTitle: textStyles.sectionTitle, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: theme.space.md }, mobileGrid: { gap: theme.space.sm }, detailPanel: { backgroundColor: theme.color.surface, borderRadius: theme.radius.md, overflow: 'hidden' }, statusRow: { minHeight: 56, flexDirection: 'row', alignItems: 'center', gap: theme.space.sm, paddingHorizontal: theme.space.md, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: theme.color.divider }, statusLabel: { ...textStyles.meta, flex: 1 }, statusValue: { ...textStyles.status, maxWidth: '55%', textAlign: 'right' } });
