import { Image, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import type { MediaRecord } from '../../../types/domain';
import { colors } from '../../../theme/tokens';
import { formatBytes, formatDuration, titleFromFilename } from '../../../lib/format';

export function MediaCard({ item, desktop, selected, onPress, onLongPress }: { item: MediaRecord; desktop: boolean; selected: boolean; onPress: () => void; onLongPress: () => void }) {
  const icon = item.state === 'synced' ? 'cloud-done-outline' : item.state === 'uploading' ? 'cloud-upload-outline' : item.state === 'error' ? 'alert-circle-outline' : 'time-outline';
  return <Pressable testID={`media-${item._id}`} accessibilityLabel={`${item.filename}, ${item.state}`} onPress={onPress} onLongPress={onLongPress} style={({ pressed }) => [styles.card, !desktop && styles.mobile, selected && styles.selected, pressed && { opacity: .72 }]}>
    <View style={[styles.visual, !desktop && styles.visualMobile]}>{item.thumbnailUrl ? <Image source={{ uri: item.thumbnailUrl }} style={styles.image as any} /> : <View style={styles.videoFallback}><Ionicons name="videocam" color={colors.muted} size={30} /><Text style={styles.fallbackText}>Thumbnail processing</Text></View>}<Text style={styles.duration}>{formatDuration(item.durationMs)}</Text></View>
    {selected ? <View style={styles.check}><Ionicons name="checkmark" color="#fff" size={16} /></View> : null}
    <View style={styles.body}><Text style={styles.title} numberOfLines={1}>{titleFromFilename(item.filename)}</Text><Text style={styles.meta}>{formatBytes(item.sizeBytes)}{item.collectionName ? ` · ${item.collectionName}` : ''}</Text><View style={styles.stateLine}><Ionicons name={icon} size={14} color={item.state === 'synced' ? colors.primary : item.state === 'error' ? colors.danger : colors.muted} /><Text style={[styles.state, item.state === 'synced' && { color: colors.primary }, item.state === 'error' && { color: colors.danger }]}>{item.state === 'synced' ? 'Synced' : item.state === 'uploading' ? 'Uploading' : item.state === 'error' ? item.syncError ?? 'Upload failed' : 'Queued'}</Text></View></View>
  </Pressable>;
}
const styles = StyleSheet.create({ card: { width: '32.15%', minWidth: 260, borderWidth: 1, borderColor: colors.border, borderRadius: 12, backgroundColor: colors.surface, overflow: 'hidden' }, mobile: { width: '100%', minWidth: 0, minHeight: 92, padding: 8, flexDirection: 'row', alignItems: 'center', overflow: 'visible' }, selected: { borderColor: colors.primary, borderWidth: 2 }, visual: { width: '100%', aspectRatio: 1.72, backgroundColor: colors.raised }, visualMobile: { width: 112, height: 72, borderRadius: 8, overflow: 'hidden' }, image: { width: '100%', height: '100%', resizeMode: 'cover' }, videoFallback: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 4 }, fallbackText: { color: colors.muted, fontSize: 10 }, duration: { position: 'absolute', right: 8, bottom: 7, color: '#fff', fontSize: 10, fontWeight: '700', borderRadius: 4, paddingHorizontal: 5, paddingVertical: 2, backgroundColor: '#000c' }, check: { position: 'absolute', zIndex: 2, right: 8, top: 8, width: 26, height: 26, borderRadius: 13, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' }, body: { flex: 1, paddingHorizontal: 14, paddingVertical: 13 }, title: { color: colors.text, fontSize: 14, fontWeight: '600' }, meta: { color: colors.muted, marginTop: 5, fontSize: 12 }, stateLine: { flexDirection: 'row', gap: 5, alignItems: 'center', marginTop: 7 }, state: { color: colors.muted, flex: 1, fontSize: 12 } });
