import { Image, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import type { MediaRecord } from '../../../types/domain';
import { theme, textStyles } from '../../../theme/tokens';
import { formatBytes, formatDuration, titleFromFilename } from '../../../lib/format';
import { backupStateLabel } from '../../../content/productCopy';

export function MediaCard({ item, desktop, selected, onPress, onLongPress }: { item: MediaRecord; desktop: boolean; selected: boolean; onPress: () => void; onLongPress: () => void }) {
  const icon = item.state === 'synced' ? 'cloud-done-outline' : item.state === 'uploading' ? 'cloud-upload-outline' : item.state === 'error' ? 'alert-circle-outline' : 'time-outline';
  const stateLabel = backupStateLabel(item.state, item.syncError);
  const stateColor = item.state === 'synced' ? theme.color.success : item.state === 'error' ? theme.color.danger : theme.color.textSecondary;
  return <Pressable testID={`media-${item._id}`} accessibilityLabel={`${item.filename}, ${stateLabel}`} onPress={onPress} onLongPress={onLongPress} style={({ pressed, hovered }: any) => [styles.card, !desktop && styles.mobile, selected && styles.selected, (pressed || hovered) && styles.interaction]}>
    <View style={[styles.visual, !desktop && styles.visualMobile]}>{item.thumbnailUrl ? <Image source={{ uri: item.thumbnailUrl }} style={styles.image as any} /> : <View style={styles.videoFallback}><Ionicons name="videocam" color={theme.color.textSecondary} size={30} /><Text style={styles.fallbackText}>Thumbnail processing</Text></View>}<Text style={styles.duration}>{formatDuration(item.durationMs)}</Text></View>
    {selected ? <View style={styles.check}><Ionicons name="checkmark" color={theme.color.white} size={16} /></View> : null}
    <View style={styles.body}><Text style={styles.title} numberOfLines={1}>{titleFromFilename(item.filename)}</Text><Text style={styles.meta}>{formatBytes(item.sizeBytes)}{item.collectionName ? ` · ${item.collectionName}` : ''}</Text><View style={styles.stateLine}><Ionicons name={icon} size={14} color={stateColor} /><Text style={[styles.state, { color: stateColor }]}>{stateLabel}</Text></View></View>
  </Pressable>;
}
const styles = StyleSheet.create({ card: { width: '32.15%', minWidth: 260, borderRadius: theme.radius.md, backgroundColor: theme.color.surface, overflow: 'hidden' }, mobile: { width: '100%', minWidth: 0, minHeight: 92, padding: theme.space.xs, flexDirection: 'row', alignItems: 'center', overflow: 'visible' }, selected: { backgroundColor: theme.color.surfaceSelected }, interaction: { opacity: 0.84 }, visual: { width: '100%', aspectRatio: 1.72, backgroundColor: theme.color.surfaceElevated }, visualMobile: { width: 112, height: 72, borderRadius: theme.radius.xs, overflow: 'hidden' }, image: { width: '100%', height: '100%', resizeMode: 'cover' }, videoFallback: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: theme.space.xxs }, fallbackText: textStyles.status, duration: { position: 'absolute', right: theme.space.xs, bottom: 7, color: theme.color.white, fontSize: 10, fontWeight: '700', borderRadius: theme.radius.xs, paddingHorizontal: 5, paddingVertical: 2, backgroundColor: theme.color.mediaOverlay }, check: { position: 'absolute', zIndex: 2, right: theme.space.xs, top: theme.space.xs, width: 26, height: 26, borderRadius: 13, backgroundColor: theme.color.accent, alignItems: 'center', justifyContent: 'center' }, body: { flex: 1, paddingHorizontal: theme.space.md, paddingVertical: theme.space.sm }, title: textStyles.cardTitle, meta: { ...textStyles.meta, marginTop: theme.space.xxs }, stateLine: { flexDirection: 'row', gap: 5, alignItems: 'center', marginTop: theme.space.xs }, state: { ...textStyles.status, flex: 1 } });
