import { ActivityIndicator, Image, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import type { MediaRecord } from '../../../types/domain';
import { theme, textStyles } from '../../../theme/tokens';
import { formatBytes, formatDate, formatDuration, titleFromFilename } from '../../../lib/format';
import { storageStateLabel } from '../../../content/productCopy';
import { ProgressBar } from '../../../components/ui/ProgressBar';
import { IconButton } from '../../../components/ui/IconButton';

type Props = { item: MediaRecord; selected: boolean; onPress: () => void; onLongPress: () => void; onAddToPlaylist?: () => void; /** Computed by the responsive grid, never inferred from percentage widths. */ width?: number; /** Progress is durable backup-activity data, not an optimistic card-only value. */ progress?: number; desktop?: boolean };

export function MediaCard({ item, selected, onPress, onLongPress, onAddToPlaylist, width, progress, desktop: _desktop }: Props) {
  const title = titleFromFilename(item.filename);
  const stateLabel = storageStateLabel(item.storage.state, item.syncError);
  return <Pressable testID={`media-${item._id}`} accessibilityRole="button" accessibilityLabel={`${item.filename}, ${stateLabel}`} accessibilityHint="Open video details. Long press to select." accessibilityState={{ selected }} onPress={onPress} onLongPress={onLongPress} style={({ pressed, hovered, focused }: any) => [styles.card, width ? { width } : styles.defaultWidth, selected && styles.selected, (pressed || hovered) && styles.interaction, focused && styles.focused]}>
    <MediaThumbnail item={item} />
    {selected ? <SelectionAffordance /> : null}
    <View style={styles.body}><MediaMetadata item={item} title={title} showSize={!width || width >= 188} /><MediaStatus item={item} progress={progress} /></View>
    {onAddToPlaylist ? <View style={styles.menu} onStartShouldSetResponder={() => true}><IconButton label={`More actions for ${title}`} name="ellipsis-horizontal" tone="surface" onPress={onAddToPlaylist} /></View> : null}
  </Pressable>;
}

export function MediaThumbnail({ item }: { item: MediaRecord }) { return <View style={styles.visual}>{item.thumbnailUrl ? <Image accessibilityLabel={`Thumbnail for ${titleFromFilename(item.filename)}`} source={{ uri: item.thumbnailUrl }} style={styles.image} /> : <View accessibilityLabel="Thumbnail processing" style={styles.videoFallback}><ActivityIndicator color={theme.color.textSecondary} /><Ionicons name="videocam-outline" color={theme.color.textSecondary} size={24} /><Text style={styles.fallbackText}>Thumbnail processing</Text></View>}<LinearGradient pointerEvents="none" colors={[theme.color.mediaGradientStart, theme.color.mediaGradientEnd]} locations={[0.38, 1]} style={styles.thumbnailGradient} /><Text accessibilityLabel={`Duration ${formatDuration(item.durationMs)}`} style={styles.duration}>{formatDuration(item.durationMs)}</Text></View>; }
export function MediaMetadata({ item, title, showSize }: { item: MediaRecord; title: string; showSize: boolean }) { return <View style={styles.metadata}><Text style={styles.title} numberOfLines={2}>{title}</Text><Text style={styles.meta} numberOfLines={1}>{formatDate(item.createdAt)}</Text>{showSize ? <Text style={styles.size} numberOfLines={1}>{formatBytes(item.sizeBytes)}</Text> : null}</View>; }
export function MediaStatus({ item, progress }: { item: MediaRecord; progress?: number }) { const active = item.storage.state === 'uploading'; if (active) { const percent = Math.round(Math.max(0, Math.min(progress ?? 0, 1)) * 100); return <View accessibilityLabel={`${percent}% uploaded`} style={styles.activeStatus}><View style={styles.activeLine}><View style={styles.progressCircle}><Text style={styles.progressText}>{percent}%</Text></View><Text style={styles.uploadingLabel}>Uploading</Text></View><ProgressBar value={progress ?? 0} accessibilityLabel={`${titleFromFilename(item.filename)} upload progress`} /></View>; } if (item.storage.cloudAvailable) return <View accessibilityLabel="Backed up to cloud" style={styles.quietCloud}><Ionicons name="cloud-done-outline" size={16} color={theme.color.success} /></View>; const tone = item.storage.state === 'failed' ? theme.color.danger : theme.color.warning; const icon = item.storage.state === 'failed' ? 'alert-circle-outline' : 'time-outline'; return <View accessibilityLabel={stateLabel(item)} style={styles.exceptionStatus}><Ionicons name={icon} size={15} color={tone} /><Text style={[styles.exceptionLabel, { color: tone }]} numberOfLines={1}>{stateLabel(item)}</Text></View>; }
function SelectionAffordance() { return <View accessibilityLabel="Selected" style={styles.check}><Ionicons name="checkmark" color={theme.color.white} size={16} /></View>; }
function stateLabel(item: MediaRecord) { return storageStateLabel(item.storage.state, item.syncError); }

const styles = StyleSheet.create({ card: { borderRadius: theme.radius.md, backgroundColor: theme.color.surface, overflow: 'hidden' }, defaultWidth: { width: 260 }, selected: { backgroundColor: theme.color.surfaceSelected }, interaction: { opacity: 0.86 }, focused: { borderWidth: 2, borderColor: theme.color.focus }, visual: { width: '100%', aspectRatio: 16 / 10, backgroundColor: theme.color.surfaceElevated, overflow: 'hidden' }, image: { width: '100%', height: '100%', resizeMode: 'cover' }, thumbnailGradient: { ...StyleSheet.absoluteFill }, videoFallback: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: theme.space.xxs }, fallbackText: textStyles.status, duration: { position: 'absolute', right: theme.space.xs, bottom: theme.space.xs, color: theme.color.white, fontSize: 11, fontWeight: '700', borderRadius: theme.radius.xs, paddingHorizontal: 6, paddingVertical: 3, backgroundColor: theme.color.mediaOverlay }, check: { position: 'absolute', zIndex: 2, right: theme.space.xs, top: theme.space.xs, width: 28, height: 28, borderRadius: 14, backgroundColor: theme.color.accent, alignItems: 'center', justifyContent: 'center' }, menu: { position: 'absolute', right: theme.space.xs, bottom: theme.space.xs }, body: { minHeight: 115, padding: theme.space.sm, paddingRight: 56, gap: theme.space.xs }, metadata: { gap: theme.space.xxs }, title: textStyles.cardTitle, meta: textStyles.meta, size: { ...textStyles.meta, color: theme.color.textTertiary }, quietCloud: { height: 17, justifyContent: 'center', alignItems: 'flex-start' }, activeStatus: { gap: theme.space.xs }, activeLine: { flexDirection: 'row', alignItems: 'center', gap: theme.space.xs }, progressCircle: { minWidth: 32, height: 32, paddingHorizontal: 3, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: theme.color.accentSubtle, borderWidth: 1, borderColor: theme.color.accent }, progressText: { ...textStyles.status, color: theme.color.white, fontSize: 10 }, uploadingLabel: { ...textStyles.status, color: theme.color.textPrimary }, exceptionStatus: { minHeight: 17, flexDirection: 'row', alignItems: 'center', gap: theme.space.xxs }, exceptionLabel: { ...textStyles.status, flex: 1 } });
