import { useEffect, useState } from 'react';
import { Platform, ScrollView, StyleSheet, Switch, Text, useWindowDimensions, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useMutation, useQuery } from 'convex/react';
import { api } from '../../../../convex/_generated/api';
import type { CollectionRecord } from '../../../types/domain';
import { colors } from '../../../theme/tokens';
import { Button } from '../../../components/ui/Button';
import { EmptyState, ErrorState, LoadingState } from '../../../components/ui/ScreenState';
import { readDeviceCollections } from '../services/deviceCollections';
import { syncCollection } from '../services/syncCollection';

export function AutoSyncScreen({ clientKey }: { clientKey: string }) {
  const rows = useQuery(api.collections.list, { clientKey }); const reconcile = useMutation(api.collections.reconcile); const setAutoSync = useMutation(api.collections.setAutoSync); const [refreshing, setRefreshing] = useState(false); const [syncing, setSyncing] = useState<string>(); const [error, setError] = useState<string>();
  const desktop = useWindowDimensions().width >= 800;
  const refresh = async () => { if (Platform.OS === 'web') return; try { setRefreshing(true); setError(undefined); const collections = await readDeviceCollections(); await reconcile({ clientKey, collections }); } catch (value) { setError(value instanceof Error ? value.message : 'Unable to read device collections'); } finally { setRefreshing(false); } };
  useEffect(() => { if (Platform.OS !== 'web') void refresh(); }, [clientKey]);
  const toggle = async (collection: CollectionRecord, enabled: boolean) => { try { setError(undefined); await setAutoSync({ clientKey, collectionId: collection._id, enabled }); if (enabled) { setSyncing(collection.name); await syncCollection(clientKey, collection); } } catch (value) { setError(value instanceof Error ? value.message : `Unable to update ${collection.name}`); } finally { setSyncing(undefined); } };
  if (rows === undefined) return <LoadingState label="Loading automatic sync settings…" />;
  return <View style={styles.screen}><View style={[styles.header, desktop && styles.desktopFrame]}><View><Text style={styles.eyebrow}>MOVE SYNC</Text><Text style={styles.heading}>AutoSync</Text></View>{Platform.OS !== 'web' ? <Button label={refreshing ? 'Scanning…' : 'Scan collections'} icon="refresh" disabled={refreshing} onPress={refresh} /> : null}</View>
    {error ? <ErrorState message={error} onRetry={refresh} /> : null}
    {Platform.OS === 'web' ? <View style={[styles.webNotice, desktop && styles.desktopFrame]}><View style={styles.noticeIcon}><Ionicons name="phone-portrait-outline" size={23} color={colors.primary} /></View><View style={styles.noticeBody}><Text style={styles.noticeTitle}>AutoSync is configured on your phone</Text><Text style={styles.noticeText}>The web app keeps your cloud library available. Choose device collections in the iOS or Android app to sync new videos in the background.</Text></View></View> : rows.length ? <ScrollView contentContainerStyle={styles.content}><View style={styles.summary}><Ionicons name="cloud-upload-outline" size={24} color={colors.primary} /><View style={{ flex: 1 }}><Text style={styles.summaryTitle}>{rows.filter(row => row.autoSync).length} collection{rows.filter(row => row.autoSync).length === 1 ? '' : 's'} syncing</Text><Text style={styles.summaryText}>Enabled collections are scanned now and periodically in the background.</Text></View></View><Text style={styles.section}>DEVICE COLLECTIONS</Text><View style={styles.panel}>{rows.map(row => <CollectionRow key={row._id} item={row as CollectionRecord} busy={Boolean(syncing)} onChange={value => toggle(row as CollectionRecord, value)} />)}</View>{syncing ? <View style={styles.syncNotice}><Ionicons name="sync" size={18} color={colors.primary} /><Text style={styles.syncText}>Syncing new videos from {syncing}…</Text></View> : null}</ScrollView> : <EmptyState title="No video collections found" message="Grant video-library access, then scan this phone again. Collection names and counts come directly from the device." action="Scan this phone" onAction={refresh} />}
  </View>;
}
function CollectionRow({ item, busy, onChange }: { item: CollectionRecord; busy: boolean; onChange: (value: boolean) => void }) { return <View style={styles.row}><View style={styles.rowIcon}><Ionicons name="albums-outline" size={20} color="#cbd5e1" /></View><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{item.name}</Text><Text style={styles.rowMeta}>{item.videoCount} video{item.videoCount === 1 ? '' : 's'} · {item.assetCount} total items</Text></View><Switch accessibilityLabel={`${item.name} automatic sync`} disabled={busy} value={item.autoSync} onValueChange={onChange} trackColor={{ false: '#3c4958', true: colors.primary }} thumbColor="#fff" /></View>; }
const styles = StyleSheet.create({ screen: { flex: 1 }, header: { minHeight: 112, padding: 22, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 15 }, desktopFrame: { width: '100%', maxWidth: 1040, alignSelf: 'center' }, eyebrow: { color: colors.primary, letterSpacing: 1.8, fontWeight: '800', fontSize: 10 }, heading: { color: colors.text, fontSize: 30, fontWeight: '700', letterSpacing: -.7, marginTop: 5 }, webNotice: { minHeight: 172, padding: 28, gap: 18, flexDirection: 'row', alignItems: 'center', borderRadius: 14, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, noticeIcon: { width: 52, height: 52, borderRadius: 13, alignItems: 'center', justifyContent: 'center', backgroundColor: '#112941' }, noticeBody: { flex: 1, maxWidth: 640 }, noticeTitle: { color: colors.text, fontSize: 18, fontWeight: '700', letterSpacing: -.2 }, noticeText: { color: colors.muted, fontSize: 14, lineHeight: 21, marginTop: 7 }, content: { width: '100%', maxWidth: 760, alignSelf: 'center', padding: 22, paddingBottom: 110 }, summary: { minHeight: 82, padding: 15, gap: 13, flexDirection: 'row', alignItems: 'center', borderRadius: 14, backgroundColor: '#0c1c2c', borderWidth: 1, borderColor: '#24618e' }, summaryTitle: { color: colors.text, fontWeight: '700' }, summaryText: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 4 }, section: { color: colors.muted, fontSize: 12, letterSpacing: 1.4, marginTop: 24, marginBottom: 10 }, panel: { borderRadius: 14, overflow: 'hidden', backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, row: { minHeight: 78, padding: 14, gap: 12, flexDirection: 'row', alignItems: 'center', borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border }, rowIcon: { width: 40, height: 40, borderRadius: 10, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.raised }, rowTitle: { color: colors.text, fontSize: 15, fontWeight: '600' }, rowMeta: { color: colors.muted, fontSize: 12, marginTop: 4 }, syncNotice: { marginTop: 15, padding: 13, borderRadius: 10, backgroundColor: colors.surface, flexDirection: 'row', gap: 9, alignItems: 'center' }, syncText: { color: colors.text } });
