import { useState } from 'react';
import { Modal, Platform, Pressable, ScrollView, StyleSheet, Text, useWindowDimensions, View } from 'react-native';
import { VideoView, useVideoPlayer } from 'expo-video';
import { Ionicons } from '@expo/vector-icons';
import { useMutation, useQuery } from 'convex/react';
import { api } from '../../../../convex/_generated/api';
import type { Id } from '../../../../convex/_generated/dataModel';
import type { MediaRecord } from '../../../types/domain';
import { colors } from '../../../theme/tokens';
import { formatBytes, formatDate, formatDuration, titleFromFilename } from '../../../lib/format';
import { IconButton } from '../../../components/ui/IconButton';
import { Button } from '../../../components/ui/Button';
import { ErrorState, LoadingState } from '../../../components/ui/ScreenState';
import { shareMedia } from '../../media/services/share';
import { removeLocalCopy } from '../services/removeLocalCopy';
import { backupStateLabel, productCopy } from '../../../content/productCopy';

export function PlayerScreen({ clientKey, mediaId, onBack }: { clientKey: string; mediaId: Id<'media'>; onBack: () => void }) {
  const item = useQuery(api.media.getById, { clientKey, id: mediaId }); const remove = useMutation(api.media.remove); const markLocalRemoved = useMutation(api.media.markLocalRemoved); const desktop = useWindowDimensions().width >= 800; const [details, setDetails] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState<string>();
  const player = useVideoPlayer(item?.videoUrl ?? null);
  if (item === undefined) return <LoadingState label="Opening video…" />;
  const media = item as MediaRecord;
  if (!media.videoUrl) return <ErrorState message="The cloud video file is unavailable." onRetry={onBack} />;
  const deleteCloudCopy = async () => { try { setBusy(true); await remove({ clientKey, id: media._id }); onBack(); } catch (value) { setError(value instanceof Error ? value.message : 'Unable to delete video'); } finally { setBusy(false); } };
  const deleteLocalCopy = async () => { if (!media.localAssetId || media.localAssetId.startsWith('picked:')) return; try { setBusy(true); await removeLocalCopy(media.localAssetId); await markLocalRemoved({ clientKey, id: media._id }); } catch (value) { setError(value instanceof Error ? value.message : 'Unable to remove the local video'); } finally { setBusy(false); } };
  const share = async () => { try { setBusy(true); await shareMedia([media]); } catch (value) { setError(value instanceof Error ? value.message : 'Unable to share video'); } finally { setBusy(false); } };
  return <View style={styles.screen}><View style={[styles.header, desktop && styles.desktopFrame]}><IconButton label={productCopy.player.backToVideos} name="chevron-back" onPress={onBack} /><Text style={styles.headerTitle} numberOfLines={1}>{titleFromFilename(media.filename)}</Text><View style={styles.headerActions}><IconButton label={productCopy.actions.share} name="share-outline" onPress={share} /><IconButton label={productCopy.player.showDetails} name="information-circle-outline" onPress={() => setDetails(true)} /></View></View>
    {error ? <View style={styles.inlineError}><Text style={styles.errorText}>{error}</Text></View> : null}
    <View style={[styles.layout, desktop && styles.layoutDesktop, desktop && styles.desktopFrame]}><View style={styles.videoPanel}><VideoView testID="video-player" player={player} style={styles.video} contentFit="contain" nativeControls /><View style={styles.caption}><Text style={styles.title}>{titleFromFilename(media.filename)}</Text><Text style={styles.captionMeta}>{media.mimeType} · {formatBytes(media.sizeBytes)} · {formatDuration(media.durationMs)}</Text></View></View>{desktop ? <Metadata item={media} busy={busy} onShare={share} onDeleteCloud={deleteCloudCopy} onDeleteLocal={Platform.OS !== 'web' && Boolean(media.localAssetId && !media.localAssetId.startsWith('picked:') && !media.localRemovedAt) ? deleteLocalCopy : undefined} /> : null}</View>
    <Modal visible={details && !desktop} animationType="slide" transparent onRequestClose={() => setDetails(false)}><Pressable style={styles.scrim} onPress={() => setDetails(false)} /><View style={styles.sheet}><View style={styles.handle} /><View style={styles.sheetHeader}><Text style={styles.sheetTitle}>{productCopy.player.detailsTitle}</Text><IconButton label="Close details" name="close" onPress={() => setDetails(false)} /></View><Metadata item={media} busy={busy} onShare={share} onDeleteCloud={deleteCloudCopy} onDeleteLocal={Platform.OS !== 'web' && Boolean(media.localAssetId && !media.localAssetId.startsWith('picked:') && !media.localRemovedAt) ? deleteLocalCopy : undefined} /></View></Modal>
  </View>;
}
function Metadata({ item, busy, onShare, onDeleteCloud, onDeleteLocal }: { item: MediaRecord; busy: boolean; onShare: () => void; onDeleteCloud: () => void; onDeleteLocal?: () => void }) { const rows = [ ['folder-outline', 'Size', formatBytes(item.sizeBytes)], ['time-outline', 'Duration', formatDuration(item.durationMs)], ['calendar-outline', 'Date', formatDate(item.createdAt)], ['location-outline', 'Location', item.locationName ?? 'Not recorded'], ['albums-outline', 'Collection', item.collectionName ?? productCopy.player.noCollection], ['cloud-done-outline', productCopy.player.storageLabel, backupStateLabel(item.state, item.syncError)] ] as const; return <ScrollView style={styles.details} contentContainerStyle={styles.detailsContent}><Text style={styles.detailsTitle}>Details</Text>{rows.map(([icon, label, value]) => <View key={label} style={styles.detailRow}><Ionicons name={icon} size={19} color={label === productCopy.player.storageLabel ? colors.primary : '#d6dee7'} /><Text style={styles.detailLabel}>{label}</Text><Text style={[styles.detailValue, label === productCopy.player.storageLabel && { color: colors.primary }]}>{value}</Text></View>)}<View style={styles.actionStack}><Button label={productCopy.actions.share} icon="share-outline" disabled={busy} onPress={onShare} />{onDeleteLocal ? <Button label={productCopy.actions.freePhoneStorage} icon="phone-portrait-outline" tone="ghost" disabled={busy} onPress={onDeleteLocal} /> : null}<Button label={productCopy.actions.removeFromCloud} icon="trash-outline" tone="danger" disabled={busy} onPress={onDeleteCloud} /></View></ScrollView>; }
const styles = StyleSheet.create({ screen: { flex: 1 }, header: { minHeight: 76, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, desktopFrame: { width: '100%', maxWidth: 1400, alignSelf: 'center' }, headerTitle: { color: colors.text, fontSize: 15, fontWeight: '700', flex: 1, textAlign: 'center' }, headerActions: { flexDirection: 'row', gap: 2 }, inlineError: { marginHorizontal: 20, padding: 10, borderRadius: 8, backgroundColor: '#3b1118' }, errorText: { color: '#fecaca' }, layout: { flex: 1 }, layoutDesktop: { flexDirection: 'row', gap: 22, paddingBottom: 44 }, videoPanel: { flex: 1, minHeight: 360, overflow: 'hidden', backgroundColor: '#000', borderRadius: 12, borderWidth: 1, borderColor: colors.border }, video: { width: '100%', flex: 1, minHeight: 300 }, caption: { paddingHorizontal: 18, paddingVertical: 16, backgroundColor: colors.surface }, title: { color: colors.text, fontSize: 18, fontWeight: '700', letterSpacing: -.3 }, captionMeta: { color: colors.muted, fontSize: 12, marginTop: 6 }, details: { width: '100%', maxWidth: 336, backgroundColor: colors.surface, borderRadius: 12, borderWidth: 1, borderColor: colors.border }, detailsContent: { padding: 16 }, detailsTitle: { color: colors.text, fontSize: 16, fontWeight: '700', marginBottom: 8 }, detailRow: { minHeight: 54, gap: 10, flexDirection: 'row', alignItems: 'center', borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border }, detailLabel: { color: '#dbe3ec', flex: 1 }, detailValue: { color: '#dbe3ec', maxWidth: '50%', textAlign: 'right', fontSize: 12 }, actionStack: { gap: 10, marginTop: 18 }, scrim: { flex: 1, backgroundColor: '#000a' }, sheet: { maxHeight: '78%', padding: 16, paddingBottom: 30, borderTopLeftRadius: 24, borderTopRightRadius: 24, backgroundColor: '#0b1520' }, handle: { width: 44, height: 5, borderRadius: 3, alignSelf: 'center', backgroundColor: '#5d6875' }, sheetHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, sheetTitle: { color: colors.text, fontWeight: '700', fontSize: 18 } });
